version: 2
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2/
  gradle-plugins:
    type: maven-repository
    url: https://plugins.gradle.org/m2/
  lukebemish:
      type: maven-repository
      url: https://maven.lukebemish.dev/releases/
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - maven-central
      - gradle-plugins
      - lukebemish
